### ISSUE TITLE
Selectors

### ISSUE THREAD

**Issue by nm2k** [html2rss/html2rss-web#337]
First, my compliments for the interesting project!

What I did:
1. cloned html2rss-web repo
2. built and ran container
3. accessed rss feeds from html2rss-configs
4. tried to generate my own feeds from .yml files and added a couple into config.yml

Basically, there are 4 main aspects of the problem:

1. Seems, some selectors (e.g. "description") are causing "Internal Server Problem". Try "https://some.domain/webentwickler-jobs.de/in.rss"

2. Other selectors are ignored e.g. "update". Basically, only "title" and "link" are displayed in rss feeds.

3. If you "docker exec -it ..." into the container for generating feeds from .yml, you face the following problem:
![image](https://user-images.githubusercontent.com/48849192/119675500-c3af5280-be45-11eb-8c42-ef6a939d6871.png)

gem env:
![image](https://user-images.githubusercontent.com/48849192/119678420-2a357000-be48-11eb-8a64-2a112c55cb7a.png)

bundler -v:
`Bundler version 2.2.18`

Gemfile.lock:
`...
BUNDLED WITH
       2.2.17
...`

4. /health_check.txt endpoint doesn't work returning "success" alongside with "Internal Server Problem"

**Comment by gildesmarais** [comment]
Hi,

thank you for opening this issue and the compliments. 😊

As you said, the problems have several aspects to it.
From a first look it seems many stem from h2r-web not making use of newly added features to the [h2r gem](https://github.com/html2rss/html2rss/commits/master). I'll create issues to not forget about these afterwards. Hopefully that improves the developer experience by giving more specific/helpful errors.

Thank you for bringing up the four aspects. I'm sure this projects benefits a once your findings are fixed. Btw, I'm open to contributions to bring this project forward from the "works for me personally" status. ;)
Now, to each one specifically:

## 1

That config requires a `region` parameter.
See a working example here: https://1.h2r.workers.dev/webentwickler-jobs.de/in.rss?region=Berlin

h2r-web should improve handle missing parameters better. IIRC h2r raises a specific error already, so it should no big deal to implement and handle exceptions nicer. 

=> https://github.com/html2rss/html2rss-web/issues/338

## 2

I assume you experienced the problem of missing attributes in the RSS with your own config?

In general, it works as intended, e.g.:

- https://1.h2r.workers.dev/cleanenergywire.org/news.rss items have `pubDate`s
- while aforementioned webentickler-jobs.de/in items have `title` and `description`.

Only a few tags from the config will make it into the feed (RSS 2.0 spec). See https://github.com/html2rss/html2rss#the-selectors

Does that help? If not, feel free to share the config where the problem occurs and we can work it out. :)

## 3

Oh, I suppose `bundler` does not setup binstubs of the *not yet released*, but used, CLI the h2r gem offers. 

=> https://github.com/html2rss/html2rss-web/issues/339

Use `bundle exec html2rss` meanwhile:

![by default 2021-05-28 at 11 38 45](https://user-images.githubusercontent.com/350021/119965265-5c5ee300-bfaa-11eb-86c8-e8c548b3037b.jpg)


Please note that the webserver (puma) in the docker containers reads the `config.yml` just once - on startup. It does not reload when there are changes to the file.

The differing bundle versions *should not* (famous last words) cause any trouble. Anyway, would be good to keep them in sync. => https://github.com/html2rss/html2rss-web/issues/340

## 4

The `/health_check.txt` endpoint just checks your own configs. As there might is a problem with your own config (see point 2), that would explain the behaviour.

Anyway, it should return a string giving some information and not just "status 500 out" 

=> https://github.com/html2rss/html2rss-web/issues/341

**Comment by gildesmarais** [comment]
I've spend several hours yesterday to bump up the application. The previous one was organically grown code from very early days of my "html to rss fiddling days".

You might want to pull/update everything and try your config again. You should already see more helpful error messages instead of "500 - ISE".

Here's the example from aspect 1 with a missing parameter: <https://1.h2r.workers.dev/webentwickler-jobs.de/in.rss>
![by default 2021-05-29 at 12 52 19](https://user-images.githubusercontent.com/350021/120067570-b8923780-c07c-11eb-8737-5d542f7ce4fd.jpg)

**Comment by nm2k** [comment]
Hi, I didn't expect such a swift response, thank you!
I'm testing your updates. It might take some time. First results indeed very good. I'll keep posting. I hope I'll be able to switch from testing to contributing as soon as I get familiar with the architecture.

**Comment by nm2k** [comment]
Hi! 2 months into personal use it wars flawlessly! Thanks for your efforts!

**Comment by gildesmarais** [comment]
Perfect, thank you for reporting these good news. Glad to hear it's running flawlessly for you :)
