### ISSUE TITLE
Support for sub-path reverse proxy

### ISSUE THREAD

**Issue by sabishiii** [html2rss/html2rss-web#409]
Hi,

Is there a way to host this site under a sub-path reverse proxy? I mean something like https://nosuchdomain.invalid/html2rss, with an Nginx config like this:

```nginx
upstream html2rss {
  server 127.0.0.1:3000;
}

server {
  # listen block and other sub-path sites would go here
  location /htm2rss/ {
    proxy_pass http://html2rss/;
  }
}
```
When I use the above Nginx site config, I'm able to download the XML files for the RSS feeds, but the browser preview does not work, since the html2rss-web site assumes that its asset files(like styles.css) are located at the root URL and does not add the /html2rss prefix.

Is there a configuration option for adding a prefix to the URLs of the site's assets? I could not find any myself...

In any case, thanks for the help and especially for this project, it's extremely useful! :)

**Comment by gildesmarais** [comment]
Hi,

thank you for your report.

There is no configuration or something for setting a sub-path. I can only imagine few places which assume the assets to be at an absolute path. Changing these places to use relative paths should be enough.

I'll check that and change it later today/this week.

Glad you find this useful.

Cheers, 
Gil
