### ISSUE TITLE
Fetch full text by following the item URL?

### ISSUE THREAD

**Issue by rsolvang** [html2rss/html2rss-web#569]
When no description or text is available (only a heading and/or an image), is html2rss able to fetch the full text of an item _by following the URL (load a new page)_, then selecting elements that contains the text, date, author etc – and add it to the generated RSS feed?

I have tried to read the available documentation but could not find such a feature described. It would be quite handy to have such a feature :smirk: One example of a site where this would be handy: https://www.op.no/debatt/

**Comment by gildesmarais** [comment]
Hi,

thank you for your issue. 

Currently that is not possible. Although I see the need for fulltext RSS feeds, I do not see it being in the scope of html2rss. (That opinion is not engraved in stone and might change.)

Fetching full text of a page could also be done on the consumer side, e.g. the rss client (Reeder does it), or with a middleware like [morss.it](https://morss.it/) or alternatives.

Have a nice weekend!
